import 'package:floor/floor.dart';
import '../../models/customer.dart';

/// Data Access Object for Customer entities.
/// Provides database operations for customer management.

@dao
abstract class CustomerDao{
  /// Retrieves all customers from the database
  /// returns a list of all Customer objects
  @Query('SELECT * FROM Customer')
  Future<List<Customer>> findAllCustomers();

  ///Retrieves a specific customer by ID
/// returns Customer object if found, null otherwise
@Query('SELECT * FROM Customer WHERE id = :id')
  Future<Customer?> findCustomerById(int id);

///inserts a new customer into the database
///The customer ID will be auto-generated by Floor
@insert
  Future<void> insertCustomer(Customer customer);

///Updates an existing customer in the database
///Customer must have a valid ID
@update
Future<void> updateCustomer(Customer customer);

///Deletes a customer by ID
///Removes the customer from the database permanently
@Query('DELETE FROM Customer WHERE id = :id')
  Future<void> delete(int id);

/// Gets the total count of customers
/// returns the number of customers in the database
@Query('SELECT COUNT(*) FROM Customer')
  Future<int?> getCustomerCount();
}