name: airline_management_system
description: "CST2335 Final Project - Customer Management Module"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  encrypted_shared_preferences: ^3.0.1
  url_launcher: ^6.3.1
  sqflite_common_ffi_web: 0.4.5+4
  sqlite3_flutter_libs: ^0.5.24
  sqflite: ^2.4.2
  path: ^1.8.3
  floor: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  floor_generator: ^1.5.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

  assets:
    - assets/translations/