import '../models/airplane.dart';
import '../database/database.dart';
import '../database/daos/airplane_dao.dart';

/// Repository class for managing Airplane data operations
class AirplaneRepository {
  late AirplaneDao _airplaneDao;
  bool _initialized = false;

  /// Initializes the database connection
  Future<void> _initializeDatabase() async {
    if (!_initialized) {
      final database = await AppDatabase.getInstance();
      _airplaneDao = database.airplaneDao;
      _initialized = true;
    }
  }

  /// Inserts a new airplane into the database
  /// [airplane] - Airplane object to be inserted (id should be null for new airplanes)
  /// Returns the ID of the inserted airplane (auto-generated by Floor)
  /// Throws exception if insertion fails
  Future<int> insertAirplane(Airplane airplane) async {
    try {
      await _initializeDatabase();

      // Get the auto-generated ID by finding the last inserted airplane
      final airplanes = await _airplaneDao.findAllAirplanes();
      return airplanes.isNotEmpty ? airplanes.last.id! : 0;
    } catch (e) {
      throw Exception('Failed to insert airplane: $e');
    }
  }

  /// Retrieves all airplanes from the database
  /// Returns a list of all Airplane objects
  /// Returns empty list if no airplanes found
  /// Throws exception if retrieval fails
  Future<List<Airplane>> getAllAirplanes() async {
    try {
      await _initializeDatabase();
      final airplanes = await _airplaneDao.findAllAirplanes();
      return airplanes;
    } catch (e) {
      throw Exception('Failed to retrieve airplanes: $e');
    }
  }

  /// Retrieves a specific airplane by ID
  /// [id] - ID of the airplane to retrieve
  /// Returns Airplane object if found, null otherwise
  /// Throws exception if retrieval fails
  Future<Airplane?> getAirplaneById(int id) async {
    try {
      await _initializeDatabase();
      return await _airplaneDao.findAirplaneById(id);
    } catch (e) {
      throw Exception('Failed to retrieve airplane by ID: $e');
    }
  }

  /// Updates an existing airplane in the database
  /// [airplane] - Airplane object with updated information
  /// Returns 1 if update successful, 0 if airplane not found
  /// Throws exception if update fails
  Future<int> updateAirplane(Airplane airplane) async {
    try {
      await _initializeDatabase();
      if (airplane.id == null) {
        throw Exception('Cannot update airplane: ID is null');
      }
      await _airplaneDao.updateAirplane(airplane);
      return 1;
    } catch (e) {
      throw Exception('Failed to update airplane: $e');
    }
  }

  /// Deletes an airplane from the database
  /// [id] - ID of the airplane to delete
  /// Returns 1 if deletion successful, 0 if airplane not found
  /// Throws exception if deletion fails
  Future<int> deleteAirplane(int id) async {
    try {
      await _initializeDatabase();
      await _airplaneDao.delete(id);
      return 1;
    } catch (e) {
      throw Exception('Failed to delete airplane: $e');
    }
  }

  /// Gets the count of total airplanes
  /// Returns the number of airplanes in the database
  Future<int> getAirplaneCount() async {
    try {
      await _initializeDatabase();
      return await _airplaneDao.getAirplaneCount() ?? 0;
    } catch (e) {
      throw Exception('Failed to get airplane count: $e');
    }
  }

  /// Validates airplane data before database operations
  /// [airplane] - Airplane object to validate
  /// Returns true if valid, throws exception with details if invalid
  bool validateAirplane(Airplane airplane) {
    if (airplane.airplaneType.trim().isEmpty) {
      throw Exception('Airplane type cannot be empty');
    }
    if (airplane.passengers <= 0) {
      throw Exception('Passenger count must be greater than 0');
    }
    if (airplane.maxSpeed.trim().isEmpty) {
      throw Exception('Maximum speed cannot be empty');
    }
    if (airplane.rangeDistance.trim().isEmpty) {
      throw Exception('Range distance cannot be empty');
    }

    return true;
  }
}